env: "local"

http_server:
  address: "localhost"
  port: 8083
  timeout: 4s
  idle_timeout: 60s
  read_timeout: 10s
  write_timeout: 10s

redis:
  host: "192.168.99.101"
  port: 6379
  password: ""
  db: 0
  

clients:
  sso:
    addr: "localhost:44044"
    timeout: 10s
    retries_count: 3

  users:
    address: "http://localhost"
    port: 8081